apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quetzalship-ingress-api
  namespace: sa
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Health del gateway (SIN rewrite)
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000

          # Swagger (opcional, pero útil)
          - path: /api-docs
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000
          - path: /api-docs-json
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000

          # Todo lo demás del API bajo /api -> reescribe quitando el prefijo
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway
                port:
                  number: 3000
