apiVersion: v1
kind: Service
metadata:
  name: fx
  namespace: sa
  labels:
    app: fx
spec:
  type: ClusterIP
  selector:
    app: fx
  ports:
    - name: grpc
      port: 50055
      targetPort: 50055
      protocol: TCP
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
