apiVersion: apps/v1
kind: Deployment
metadata:
  name: fx
  namespace: sa
  labels:
    app: fx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fx
  template:
    metadata:
      labels:
        app: fx
    spec:
      containers:
        - name: fx
          image: rmiguel12/quetzalship-fx:main-dc22a9a
          ports:
            - name: grpc
              containerPort: 50055
            - name: http
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: fx-config
