apiVersion: v1
kind: Service
metadata:
  name: fx
  labels:
    app: fx
spec:
  type: ClusterIP
  selector:
    app: fx
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 3001
      targetPort: 3001
