apiVersion: v1
kind: ConfigMap
metadata:
  name: fx-config
  namespace: sa
data:
  PORT: "3001"

  REDIS_HOST: "34.30.195.87"
  REDIS_PORT: "6379"
  REDIS_TTL: "3600"

  FX_PRIMARY_API_URL: "https://api.exchangerate-api.com/v4/latest"
  FX_SECONDARY_API_URL: "https://api.frankfurter.app/latest"
  FX_TIMEOUT: "5000"
  FX_RETRY_ATTEMPTS: "3"
  FX_RETRY_DELAY: "1000"

  CIRCUIT_BREAKER_THRESHOLD: "50"
  CIRCUIT_BREAKER_TIMEOUT: "60000"
  CIRCUIT_BREAKER_RESET_TIMEOUT: "30000"
